title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Jie Cao

domain: "mlciv.com"
baseurl: ""

twitter_hashtag: mlciv_jiessie
github_username: mlciv
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
